[build]
  command = "npm install && npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
